env:
  - TESTDIR=api
command:
  - cd $TESTDIR && npm install
  - NODE_ENV=test npm test
    # - docker-compose -f docker-compose.production.yml
    # - docker-compose -f docker-compose.test.yml up -d
    # - docker-compose -f docker-compose.test.yml run npm run test
