# node:
#   build: ./node
#   volumes:
#     # Mount local dir for development
#     - "./node:/usr/src/app"
#   ports:
#     - "80:3000"
#   links:
#     - couchdb
#   env_file:
#     - ./.env_dev.env

database:
  image: tutum/couchdb
  ports:
    - "5984:5984"
