var tweets = [
  { created_at: 'Fri May 23 20:24:47 +0000 2014',
  id: 469937002558029800,
  id_str: '469937002558029824',
  text: '@littletreestyle testafgsvgsgosj #digitalheroes2014',
  source: '<a href="http://itunes.apple.com/us/app/twitter/id409789998?mt=12" rel="nofollow">Twitter for Mac</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 2390559389,
  in_reply_to_user_id_str: '2390559389',
  in_reply_to_screen_name: 'littletreestyle',
  user: 
   { id: 9351682,
     id_str: '9351682',
     name: 'Scotty Vernon',
     screen_name: 'KingScooty',
     location: 'Manchester, England',
     url: 'http://www.kingscooty.com/',
     description: 'Interactive HTML5/JS dev for the UKs biggest & brightest agencies. Animation, Games, Footy, Summer & Music lover; Obsessive perfectionist; SmashingMag author.',
     protected: false,
     followers_count: 557,
     friends_count: 509,
     listed_count: 18,
     created_at: 'Wed Oct 10 13:33:47 +0000 2007',
     favourites_count: 593,
     utc_offset: 3600,
     time_zone: 'London',
     geo_enabled: true,
     verified: false,
     statuses_count: 9331,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: '181818',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/118975436/twitter_bg-kingscooty-v2.jpg',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/118975436/twitter_bg-kingscooty-v2.jpg',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/1427254999/profile-picture_normal.jpg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/1427254999/profile-picture_normal.jpg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/9351682/1350333073',
     profile_link_color: '64BDE3',
     profile_sidebar_border_color: 'FFFFFF',
     profile_sidebar_fill_color: '252429',
     profile_text_color: '555555',
     profile_use_background_image: true,
     default_profile: false,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  favorite_count: 0,
  entities: 
   { hashtags: [ [Object] ],
     symbols: [],
     urls: [],
     user_mentions: [ [Object] ] },
  favorited: false,
  retweeted: false,
  filter_level: 'medium',
  lang: 'in' },

{ created_at: 'Fri May 23 20:26:29 +0000 2014',
  id: 469937430226010100,
  id_str: '469937430226010112',
  text: '@KingScooty vnvhufcucgu #digitalheroes2014',
  source: '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 9351682,
  in_reply_to_user_id_str: '9351682',
  in_reply_to_screen_name: 'KingScooty',
  user: 
   { id: 2390559389,
     id_str: '2390559389',
     name: 'Catherine',
     screen_name: 'littletreestyle',
     location: '',
     url: null,
     description: null,
     protected: false,
     followers_count: 2,
     friends_count: 8,
     listed_count: 0,
     created_at: 'Fri Mar 07 09:15:21 +0000 2014',
     favourites_count: 0,
     utc_offset: null,
     time_zone: null,
     geo_enabled: true,
     verified: false,
     statuses_count: 13,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/441866126625374208/UdgJmCnn_normal.jpeg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/441866126625374208/UdgJmCnn_normal.jpeg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/2390559389/1394184072',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     default_profile: true,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  favorite_count: 0,
  entities: 
   { hashtags: [ [Object] ],
     symbols: [],
     urls: [],
     user_mentions: [ [Object] ] },
  favorited: false,
  retweeted: false,
  filter_level: 'medium',
  lang: 'tl' }
];

exports.tweets = tweets;